apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-helm-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nginx-helm-chart.name" . }}
    helm.sh/chart: {{ include "nginx-helm-chart.chart" . }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: {{ .Values.nginx.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "nginx-helm-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
